name: financely
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  envied: ^0.3.0+3
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter:
    sdk: flutter
  http: ^1.1.0
  iconsax: ^0.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
